### ISSUE TITLE
New rule TrailingWhitespace doesn't work with version 1.0

### ISSUE THREAD

**Issue by davidk1** [boakley/robotframework-lint#67]
For each line in **.robot** and **.resource** files I get warning message:

_.......: Line has trailing whitespace (TrailingWhitespace)_

I use PyCharm editor and there are no trailing whitespaces detected in the file, so why the rflint detects it?

**Comment by ltdemian** [comment]
Same here. Replacing 'split("\n")' with 'splitlines()' fixes the issue.

**Comment by fperrin** [comment]
Shot in the dark: would that file have DOS-style end-of-lines (or worse, mixed-style end-of-lines)?

Depending on how the file is read (which encoding, and whether it's opened in binary mode), Python's universal newlines might not strip `\r` at the right time. Although to @ltdemian 's point, it's probably splitlines that should be used, rather than `split("\n")`.

**Comment by davidk1** [comment]
@fperrin file-encoding: UTF-8, Pycharm on Windows 10, line-separator: CRLF, robotframework-lint=1.0
1. With lint=0.9 there is no difference in results between changing line-separator: CRLF, LF and CR
2. With lint=1.0 I am getting different results for every possible setting of line-separator: CR, LF and CRLF

**Comment by fperrin** [comment]
I think you're right, my mention of mixed EOL is not relevant. That's a problem in rflint, and we should use splitlines. That's an easy enough change, but unfortunately rflint isn't seeing much activity these days.
